# Generated by Django 5.0.7 on 2026-02-23 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='additional_documents',
        ),
        migrations.RemoveField(
            model_name='application',
            name='passport_copy',
        ),
        migrations.RemoveField(
            model_name='application',
            name='passport_photo',
        ),
        migrations.AddField(
            model_name='application',
            name='cancellations_used',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times the student has cancelled the discovery meeting (max 3)'),
        ),
        migrations.AddField(
            model_name='application',
            name='consultant_name',
            field=models.CharField(blank=True, help_text='Name of the consultant assigned to this application', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='consultant_title',
            field=models.CharField(blank=True, default='Visa Consultant', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='meeting_date',
            field=models.DateField(blank=True, help_text='Scheduled date of the discovery meeting', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='meeting_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='meeting_time',
            field=models.CharField(blank=True, help_text='e.g. 10:00 AM - 10:30 AM', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/documents/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('file_size', models.CharField(help_text='e.g. 1.2 MB or 340 KB', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
