# Generated by Django 5.0.7 on 2026-04-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationmessage'),
        ('calls', '0006_remove_callsession_agent_remove_callevaluation_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmessage',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_messages', to='calls.callsession'),
        ),
    ]
