# Generated by Django 5.0.7 on 2026-04-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationmessage_chat_session'),
        ('providers', '0002_serviceprovider_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='providers.serviceprovider'),
        ),
    ]
