# Generated by Django 5.0.7 on 2026-03-26 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_right_documents', models.BooleanField()),
                ('meets_eligibility', models.BooleanField()),
                ('communication_score', models.PositiveSmallIntegerField()),
                ('understands_process', models.BooleanField()),
                ('answered_satisfactorily', models.BooleanField()),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('more_documents', 'Need More Documents')], max_length=20)),
                ('readiness_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to='calls.agent')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='calls.callsession')),
            ],
        ),
    ]
