# Generated by Django 5.0.7 on 2026-04-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='pending', max_length=20),
        ),
    ]
