# Generated by Django 5.0.7 on 2026-04-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_alter_agent_is_active_alter_agent_status'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsession',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='callevaluation',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='calldecline',
            name='agent',
        ),
        migrations.AddField(
            model_name='calldecline',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declines', to='providers.serviceprovider'),
        ),
        migrations.AddField(
            model_name='callevaluation',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to='providers.serviceprovider'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='providers.serviceprovider'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
