# Generated by Django 5.0.7 on 2026-04-22 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('travel_consultant', 'Travel Consultant'), ('visa_agency', 'Visa Agency'), ('tour_operator', 'Tour Operator'), ('immigration_consultant', 'Immigration Consultant'), ('other', 'Other')], default='other', max_length=50)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='service_providers/profiles/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='service_providers/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('verification_call_scheduled', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
