# Generated by Django 5.0.7 on 2026-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
