# Generated by Django 5.0.7 on 2026-05-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_alter_influencer_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='platform',
            field=models.CharField(max_length=500),
        ),
    ]
