# Generated by Django 5.0.7 on 2026-03-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(blank=True, choices=[('student_visa', 'Student Visa'), ('work_visa', 'Work Visa'), ('tourist_visa', 'Tourist Visa'), ('business_visa', 'Business Visa'), ('medical_visa', 'Medical Visa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
