# Generated by Django 5.0.7 on 2026-03-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_category_package_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='package',
            name='admission_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='application_fees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='course_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='covers_accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='covers_airport_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='covers_daily_tours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='covers_flight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='covers_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='covers_local_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='covers_visa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='post_study_work_visa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='trip_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='tuition_fees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='university_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='visa_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='visa_required',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('tourist', 'Tourist'), ('business', 'Business'), ('medical', 'Medical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='processing_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
