# Generated by Django 5.0.7 on 2026-04-14 06:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_course_city_package_course_expectations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
