# Generated by Django 5.0.7 on 2026-04-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_packageimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
