# Generated by Django 5.0.7 on 2026-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_package_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service_id',
            field=models.CharField(blank=True, default='0000', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
