# Generated by Django 5.0.7 on 2026-04-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_alter_package_service_id'),
        ('providers', '0002_serviceprovider_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='providers.serviceprovider'),
        ),
    ]
