# Generated by Django 5.0.7 on 2026-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_package_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='post_status',
            field=models.CharField(blank=True, choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20, null=True),
        ),
    ]
