# Generated by Django 5.0.7 on 2026-04-22 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sp_application_received', 'SP Application Received'), ('sp_call_scheduled', 'Verification Call Scheduled'), ('sp_approved', 'SP Application Approved'), ('sp_rejected', 'SP Application Rejected'), ('call_request', 'Call Request'), ('call_accepted', 'Call Accepted'), ('call_declined', 'Call Declined'), ('call_completed', 'Call Completed'), ('evaluation_submitted', 'Evaluation Submitted'), ('package_application', 'New Package Application'), ('application_status_update', 'Application Status Update')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
